### ISSUE TITLE
Missing Modrinth gallery image

### ISSUE THREAD

**Issue by triphora** [jonathan-iksjssen/onyx-sans#1]
Hi there!
I regret to inform that a Modrinth bug seems to have made about half of the [gallery images](https://modrinth.com/resourcepack/onyx-sans/gallery) completely go poof. Luckily, I was able to restore almost all of them, with the exception of the "International Maritime Signal Flags" image because its SHA1 hash didn't match that of the image in the GitHub readme like the others did.
Is it possible for you to delete and reupload that one image?
Thanks so much, and great work on the font pack! I'm using it on my own MC instance now :)
~ Emma, Modrinth admin

**Comment by romeodisk** [comment]
Good evening! The image in question has been restored. Thanks for catching the bug, and I'm glad you like the font pack! Take care.

* Jonathan Iksjssen *
